/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.AlunoDAO;
import controller.CursoDAO;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Aluno;
import model.Curso;

/**
 *
 * @author sala308b
 */
public class FrmAlunos extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmDisciplina
     */
    public FrmAlunos() {
        initComponents();
        popularCursos();
        popularAlunos();
    }
    
    public void popularCursos(){
        //DefaultComboBoxModel dm =  (DefaultComboBoxModel) cboCursos.getModel();
        DefaultComboBoxModel dm = new DefaultComboBoxModel();
 
        dm.removeAllElements();
        CursoDAO cursoDAO = new CursoDAO();
        
        cursoDAO.listar().forEach( (c) -> {
             dm.addElement(c.getId() + "-" + c.getNome());
            
        });     
        cboCursos.setModel(dm);
    }
    
    public void popularAlunos(){
        DefaultTableModel dtm = (DefaultTableModel) tblAlunos.getModel();
        dtm.setColumnCount(0);
        dtm.setNumRows(0);
        
        String[] colunas = {"ID", "NOME", "CURSO" };
        
        dtm.setColumnIdentifiers(colunas);
        
        AlunoDAO alunoDAO = new AlunoDAO();
        
        alunoDAO.listar().forEach( (a)->{
          CursoDAO cursoDAO = new CursoDAO();
          
          Curso curso = new Curso();
          curso.setId( a.getCurso().getId() );
          
          Curso cursoAluno = new Curso();
          cursoAluno = cursoDAO.pesquisar(curso);
          String s = String.valueOf( cursoAluno.getId() ) + "-" + cursoAluno.getNome(); 
                    
          String[] linha = { String.valueOf(a.getAlunoId()), a.getNome(), s  };  
          dtm.addRow(linha);
          
        });
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cboCursos = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAlunos = new javax.swing.JTable();
        btnNovo = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnPesquisar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Administração de Alunos");

        jLabel2.setText("ID");

        jLabel3.setText("Nome");

        txtId.setName("txtId"); // NOI18N

        txtNome.setName("txtNome"); // NOI18N

        jLabel4.setText("Curso");

        cboCursos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboCursos.setName("cboCursos"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(cboCursos, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addGap(1, 1, 1)
                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cboCursos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tblAlunos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblAlunos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAlunosMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblAlunosMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tblAlunosMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tblAlunos);

        btnNovo.setText("Novo");
        btnNovo.setName("btnNovo"); // NOI18N
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnSalvar.setText("Salvar");
        btnSalvar.setName("btnSalvar"); // NOI18N
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.setName("btn/excluir"); // NOI18N

        btnPesquisar.setText("Pesquisar");
        btnPesquisar.setName("btnPesquisar"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 594, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(btnNovo)
                .addGap(25, 25, 25)
                .addComponent(btnSalvar)
                .addGap(25, 25, 25)
                .addComponent(btnExcluir)
                .addGap(25, 25, 25)
                .addComponent(btnPesquisar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNovo)
                    .addComponent(btnSalvar)
                    .addComponent(btnExcluir)
                    .addComponent(btnPesquisar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblAlunosMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAlunosMouseReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_tblAlunosMouseReleased

    private void tblAlunosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAlunosMousePressed
        // TODO add your handling code here:

    }//GEN-LAST:event_tblAlunosMousePressed

    private void tblAlunosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAlunosMouseClicked
        // TODO add your handling code here:
       int linha = tblAlunos.getSelectedRow();
        
        txtId.setText( tblAlunos.getModel().getValueAt(linha, 0).toString()  );
        txtNome.setText( tblAlunos.getModel().getValueAt(linha, 1).toString()  );
        
        cboCursos.setSelectedItem(tblAlunos.getModel().getValueAt(linha, 2)   );
    }//GEN-LAST:event_tblAlunosMouseClicked

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        // TODO add your handling code here:
        txtId.setText("0");
        txtNome.setText("0");
        btnNovo.setEnabled(false);
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
        
        Aluno aluno = new Aluno();
        aluno.setAlunoId( Integer.valueOf( txtId.getText()) );
        aluno.setNome(txtNome.getText());
        
        Curso curso = new Curso();
        curso.setId( Integer.parseInt( cboCursos.getModel().getSelectedItem().toString().split("-")[0] ) );
        curso.setNome(  cboCursos.getModel().getSelectedItem().toString().split("-")[1]  );
        aluno.setCurso(curso);
       
        //Aluno pesq = new AlunoDAO().pesquisar(aluno);
        
        //if ( pesq.getAlunoId() == Integer.parseInt( txtId.getText() )  &&  pesq.getNome().equals( txtNome.getText() ) ){
          
             //if ( JOptionPane.showConfirmDialog (null,"Aluno já está cadastrado.","Aluno já cadastrado", JOptionPane.YES_NO_OPTION ) == 0 ) {
              if (  txtId.getText().equals("0") ){ 
                    if ( new AlunoDAO().incluir(aluno) ){
                        JOptionPane.showConfirmDialog(null, "Aluno salvo com sucesso.");
                    } else {
                        JOptionPane.showConfirmDialog(null, "Erro ao tentar cadastrar o aluno.");
                    }
              } else {
                   if ( new AlunoDAO().atualizar(aluno) ){
                    JOptionPane.showMessageDialog(null,"Cadastro do aluno foi atualizado");
                    }        
              }
                  
             popularAlunos();       
    }//GEN-LAST:event_btnSalvarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cboCursos;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblAlunos;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
